filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    log_type: nginx.access
  tags: nginx_access

# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/nginx/access.log
#   fields:
#     log_type: nginx.access
#   tags: nginx.access

# - type: log
#   enabled: true
#   paths:
#     - /var/log/app/*.log
# filebeat:
#   prospectors:
#     - input_type: log
#       paths:
#         - /var/log/nginx/access.log
#       tags: ["nginx.access"]

#     - input_type: log
#       paths:
#         - /var/log/nginx/error.log
#       tags: ["nginx.error"]

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  # FIXME: Cannot reach the hosts of Logstash

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "changeme"
setup.kibana:
  host: "http://kibana:5601"
  username: "kibana_system"
  password: "changeme"